const normal = [
  [1,'Applejack',9,6,3,8],
  [2,'Rainbow Dash',6,9,3,8],
  [3,'Twilight Sparkle',4,6,9,8],
  [4,'Pinkie Pie',5,8,6,9],
  [5,'Fluttershy',3,7,5,8],
  [6,'Rarity',4,5,8,7],
  [7,'Spike',6,5,4,8],
  [8,'Princess Celestia',8,8,9,8],
  [9,'Princess Luna',7,8,9,9],
  [10,'Starlight Glimmer',4,7,9,8],
  [11,'Princess Cadance',5,6,8,9],
  [12,'Flurry Heart',2,6,9,8],
  [13,'Trixie Lulamoon',3,6,8,7],
  [14,'Sunset Shimmer',5,7,9,8],
  [15,'Tempest Shadow',9,8,5,8],
  [16,'Shining Armor',9,6,7,8],
  [17,'Cozy Glow',2,8,6,8],
  [18,'Apple Bloom',5,5,3,7],
  [19,'Sweetie Belle',3,5,7,7],
  [20,'Scootaloo',4,9,2,7],
  [21,'Babs Seed',6,6,2,7],
  [22,'Diamond Tiara',2,5,4,6],
  [23,'Silver Spoon',2,5,4,6],
  [24,'Twist',2,4,3,7],
  [25,'Luster Dawn',3,6,9,7],
  [26,'Big Macintosh',9,4,1,9],
  [27,'Granny Smith',5,3,2,8],
  [28,'Pear Butter',5,5,4,8],
  [29,'Bright Mac',8,6,2,9],
  [30,'Aunt Holiday',3,6,4,7],
  [31,'Auntie Lofty',3,6,4,7],
  [32,'Sugar Belle',3,5,6,8],
  [33,'Maud Pie',9,3,4,9],
  [34,'Limestone Pie',9,6,2,8],
  [35,'Marble Pie',3,4,5,7],
  [36,'Cloudy Quartz',6,3,4,8],
  [37,'Igneous Rock Pie',8,3,2,9],
  [38,'Fancy Pants',4,6,6,7],
  [39,'Fleur de Lis',3,6,6,7],
  [40,'Suri Polomare',3,7,6,7],
  [41,'Coco Pommel',3,6,4,7],
  [42,'Hoity Toity',3,6,5,7],
  [43,'Photo Finish',2,7,5,7],
  [44,'Sapphire Shores',4,7,4,9],
  [45,'Prim Hemline',3,5,5,7],
  [46,'Trenderhoof',3,7,4,7],
  [47,'Vinyl Scratch',4,9,8,8],
  [48,'Octavia Melody',4,6,4,8],
  [49,'Lyra Heartstrings',3,6,7,7],
  [50,'Sweetie Drops',5,5,3,8],
  [51,'Derpy Hooves',4,8,2,9],
  [52,'Doctor Hooves',3,7,6,8],
  [53,'Minuette',3,7,7,8],
  [54,'Moondancer',3,5,9,7],
  [55,'Spitfire',7,9,2,9],
  [56,'Soarin',7,9,2,8],
  [57,'Fleetfoot',6,9,2,8],
  [58,'Lightning Dust',6,9,2,9],
  [59,'Misty Fly',5,9,2,8],
  [60,'Cheerilee',4,5,4,8]
].map(([n,name,strength,speed,magic,energy]) => ({
  id:`n${String(n).padStart(2,'0')}`,
  type:'normal',
  name,
  strength,
  speed,
  magic,
  energy,
  image:n===17?'/assets/cards_fixes/17_Cozy_Glow.webp':`/assets/cards/${String(n).padStart(2,'0')}_${name.replaceAll(' ','_')}.webp`
}));

const specials = [
  {id:'s61',type:'special',name:'Twilight Sparkle – Spezialkarte',effect:'twilight',text:'Nimm 2 neue Karten.',useIcon:'✦',useLabel:'Jede Kategorie',image:'/assets/specials/61_Spezial_Twilight_Sparkle.webp'},
  {id:'s62',type:'special',name:'Rainbow Dash – Sonic Rainboom',effect:'rainbow',text:'+2 Schnelligkeit für deine gewählte Karte.',useIcon:'⚡',useLabel:'Nur Schnelligkeit',image:'/assets/specials/62_Spezial_Rainbow_Dash_Sonic_Rainboom.webp'},
  {id:'s63',type:'special',name:'Applejack – Ehrliche Arbeit',effect:'applejack',text:'+1 Stärke für deine gewählte Karte.',useIcon:'🏋️',useLabel:'Nur Stärke',image:'/assets/specials/63_Spezial_Applejack.webp'},
  {id:'s64',type:'special',name:'Pinkie Pie – Überraschungsparty',effect:'pinkie',text:'Ziehe 1 neue Karte.',useIcon:'✦',useLabel:'Jede Kategorie',image:'/assets/specials/64_Spezial_Pinkie_Pie.webp'},
  {id:'s65',type:'special',name:'Fluttershy – Sanfte Hilfe',effect:'fluttershy',text:'Sieh dir 2 Karten an und behalte 1.',useIcon:'✦',useLabel:'Jede Kategorie',image:'/assets/specials/65_Spezial_Fluttershy.webp'},
  {id:'s66',type:'special',name:'Rarity – Perfekte Auswahl',effect:'rarity',text:'Tausche 1 Handkarte gegen eine neue.',useIcon:'✦',useLabel:'Jede Kategorie',image:'/assets/specials/66_Spezial_Rarity.webp'},

  {id:'s67',type:'special',name:'Tirek',effect:'tirek',text:'Wähle einen Gegner: Der Wert seiner Karte sinkt in dieser Runde um 2.',useIcon:'🔻',useLabel:'Gegner schwächen',image:'/assets/specials_new/67_Tirek.png'},
  {id:'s68',type:'special',name:'Königin Chrysalis',effect:'chrysalis',text:'Kopiere die zuletzt von einem Gegner ausgespielte Spezialkarte dieser Runde.',useIcon:'♟',useLabel:'Effekt kopieren',image:'/assets/specials_new/68_Koenigin_Chrysalis.png'},
  {id:'s69',type:'special',name:'Storm King',effect:'stormking',text:'Bei einem Gleichstand in Schnelligkeit erhält deine Karte +2.',useIcon:'⚡',useLabel:'Schnelligkeits-Gleichstand',image:'/assets/specials_new/69_Storm_King.png'},
  {id:'s70',type:'special',name:'Flim und Flam',effect:'flimflam',text:'Ziehe 1 normale Karte und lege danach 1 Handkarte ab.',useIcon:'🎩',useLabel:'Doppelter Deal',image:'/assets/specials_new/70_Flim_und_Flam.png'},
  {id:'s71',type:'special',name:'Cozy Glow',effect:'cozy',text:'Wähle einen Gegner: Er legt zufällig 1 Handkarte ab und zieht 1 normale Karte.',useIcon:'🎀',useLabel:'Falsches Lächeln',image:'/assets/specials_new/71_Cozy_Glow.png'},
  {id:'s72',type:'special',name:'Sludge',effect:'sludge',text:'Wähle einen Gegner und bestimme selbst 1 Karte aus seiner Hand, die er ablegen muss.',useIcon:'🐉',useLabel:'Karte bestimmen',image:'/assets/specials_new/72_Sludge.png'},
  {id:'s73',type:'special',name:'Diamond Dogs',effect:'diamonddogs',text:'Ziehe 2 normale Karten und behalte 1 davon.',useIcon:'💎',useLabel:'Graben nach Schätzen',image:'/assets/specials_new/73_Diamond_Dogs.png'},
  {id:'s74',type:'special',name:'Changeling',effect:'changeling',text:'Du darfst in dieser Runde sofort 1 weitere Spezialkarte einsetzen.',useIcon:'🪽',useLabel:'Schwarmruf',image:'/assets/specials_new/74_Changeling.png'},
  {id:'s75',type:'special',name:'Nightmare Moon',effect:'nightmare',text:'Die Kategorie der nächsten Runde ist automatisch Magie.',useIcon:'🌙',useLabel:'Ewige Nacht',image:'/assets/specials_new/75_Nightmare_Moon.png'},
  {id:'s76',type:'special',name:'Hydra',effect:'hydra',text:'Wenn du diese Runde verlierst, ziehst du danach 1 zusätzliche normale Karte.',useIcon:'🐲',useLabel:'Viele Köpfe',image:'/assets/specials_new/76_Hydra.png'},
  {id:'s77',type:'special',name:'Bugbear',effect:'bugbear',text:'Ein Gegner deiner Wahl setzt diese Runde aus.',useIcon:'🐝',useLabel:'Runde aussetzen',image:'/assets/specials_new/77_Bugbear.png'},
  {id:'s78',type:'special',name:'Manticore',effect:'manticore',text:'Nimm 1 Karte aus einem Ablagestapel zurück auf deine Hand.',useIcon:'🦁',useLabel:'Karte zurückholen',image:'/assets/specials_new/78_Manticore.png'},
  {id:'s79',type:'special',name:'Timberwolves',effect:'timberwolves',text:'Spiele diese Runde 2 normale Karten. Der höhere Wert der Kategorie zählt.',useIcon:'🌲',useLabel:'Zweite normale Karte',image:'/assets/specials_new/79_Timberwolves.png'},
  {id:'s80',type:'special',name:'Grogar',effect:'grogar',text:'Wähle die Kategorie dieser Runde selbst aus.',useIcon:'🔔',useLabel:'Kategorie bestimmen',image:'/assets/specials_new/80_Grogar.png'},
  {id:'s81',type:'special',name:'King Sombra',effect:'sombra',text:'Deine Karte ist diese Runde vor gegnerischen Effekten geschützt. Wähle zusätzlich einen Gegner: -2 Stärke.',useIcon:'💠',useLabel:'Schatten der Herrschaft',image:'/assets/specials_new/81_King_Sombra.png'},
  {id:'s82',type:'special',name:'Daybreaker',effect:'daybreaker',text:'Gewinne diese Runde automatisch, sobald du deine normale Karte gelegt hast.',useIcon:'☀️',useLabel:'Automatischer Rundensieg',image:'/assets/specials_new/82_Daybreaker.png'},
  {id:'s83',type:'special',name:'Iron Will',effect:'ironwill',text:'Wenn diese Karte ausgespielt wird, darf in dieser Runde niemand ein Artefakt ziehen.',useIcon:'💪',useLabel:'Artefakte blockieren',image:'/assets/specials_new/83_Iron_Will.png'},
  {id:'s84',type:'special',name:'Pony of Shadows',effect:'ponyshadows',text:'Wähle einen Gegner: Seine ausgespielte Karte zählt diese Runde nicht.',useIcon:'🌑',useLabel:'Verdunkle das Feld',image:'/assets/specials_new/84_Pony_of_Shadows.png'},
  {id:'s85',type:'special',name:'Windigos',effect:'windigos',text:'Eingefrorene Herzen: Alle außer dir setzen diese Runde aus.',useIcon:'❄️',useLabel:'Eingefrorene Herzen',image:'/assets/specials_new/85_Windigos.png'},
  {id:'s86',type:'special',name:'Sunset Shimmer',effect:'sunset',text:'Sieh dir die obersten 3 normalen Karten an und nimm 1 davon auf die Hand.',useIcon:'🔥',useLabel:'Blick voraus',image:'/assets/specials_new/86_Sunset_Shimmer.png'},
  {id:'s87',type:'special',name:'Starlight Glimmer',effect:'starlight',text:'Alle Gegner müssen in dieser Runde 1 Handkarte ablegen.',useIcon:'✦',useLabel:'Gleichschaltung',image:'/assets/specials_new/87_Starlight_Glimmer.png'},
  {id:'s88',type:'special',name:'The Great and Powerful Trixie',effect:'trixie',text:'Hebe negative gegnerische Spezialeffekte auf, die dich in dieser Runde betreffen.',useIcon:'🎩',useLabel:'Blendwerk',image:'/assets/specials_new/88_The_Great_and_Powerful_Trixie.png'},
  {id:'s89',type:'special',name:'Ahuizotl',effect:'ahuizotl',text:'Wähle einen Gegner nachdem er seine Karte gelegt hat: Sein Wert sinkt um 2.',useIcon:'🗿',useLabel:'Fallensteller',image:'/assets/specials_new/89_Ahuizotl.png'},
  {id:'s90',type:'special',name:'The Mane-iac',effect:'maneiac',text:'Wähle einen Gegner und bestimme selbst, welche Handkarte er ablegt.',useIcon:'🟢',useLabel:'Totale Kontrolle',image:'/assets/specials_new/90_The_Mane_iac.png'},
  {id:'s91',type:'special',name:'Lightning Dust',effect:'lightningdust',text:'Wähle einen Gegner, der diese Runde automatisch verliert.',useIcon:'⚡',useLabel:'Rücksichtsloser Angriff',image:'/assets/specials_new/91_Lightning_Dust.png'},
  {id:'s92',type:'special',name:'Gilda Griffon',effect:'gilda',text:'Wähle einen Gegner und nimm zufällig 1 Karte aus seiner Hand.',useIcon:'🦅',useLabel:'Krallehieb',image:'/assets/specials_new/92_Gilda_Griffon.png'},
];
const artifacts = [
  {id:'a01',type:'artifact',artifactKey:'elements',name:'Elemente der Harmonie',image:'/assets/artifacts/01_Elemente_der_Harmonie.png'},
  {id:'a02',type:'artifact',artifactKey:'crystalheart',name:'Kristall Herz',image:'/assets/artifacts/02_Kristall_Herz.png'},
  {id:'a03',type:'artifact',artifactKey:'starswirl',name:'Star Swirls Tagebuch',image:'/assets/artifacts/03_Star_Swirls_Tagebuch.png'}
];

const byId = Object.fromEntries([...normal,...specials,...artifacts].map(c=>[c.id,c]));
module.exports={normal,specials,artifacts,byId};
